### ISSUE TITLE
Laravel 9 compatibility

### ISSUE THREAD

**Issue by imClement** [sawirricardo/laravel-web3#1]
Hello, 

Is there any updated planned for Laravel 9 compatibility ? 
I tried to install it and there is a illuminate/contracts ^8.37 problem. 

Thank you,

**Comment by sawirricardo** [comment]
Hi @NewBuidler Thanks for using this package! I've submitted a commit which should resolve this. also tagged 1.0.0. Feel free to open this again if you encounter any issues!

**Comment by imClement** [comment]
Sorry to keep the topic on without having issues but I want to thank you for the quick reaction and for developing a package that it is easy to understand, set-up and use.

**Comment by sawirricardo** [comment]
Your welcome! If you still have any questions, please let me know
